yaml
name: Auto PR from Issues

on:
  issues:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Get issue description
        id: get_issue
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER" | jq -r '.body')
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_ENV
          echo "Processing issue #$ISSUE_NUMBER"

      - name: Generate code with script
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: |
          python generate_code.py "${{ env.ISSUE_BODY }}"

      - name: List generated files
        run: |
          ls -la  # Для отладки: показывает сгенерированные файлы

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B "auto-issue-${{ github.event.issue.number }}"
          git add .
          git commit -m "Auto-generated code for issue #${{ github.event.issue.number }}" || echo "Нет изменений для коммита"
          git push origin "auto-issue-${{ github.event.issue.number }}" --force

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "auto-issue-${{ github.event.issue.number }}"
          base: "main"
          title: "Automated PR for Issue #${{ github.event.issue.number }}"
          body: |
            This PR contains auto-generated code by Grok 3 based on issue #${{ github.event.issue.number }}.
            Please review the generated code before merging.
          labels: automated, pending-review
          reviewers: ${{ github.actor }}
